googlemaps/js-route-optimization-app

application/frontend/src/app/shared/pipes/distance-limit.pipe.ts
application/frontend/src/app/shared/pipes/duration-limit.pipe.ts
application/frontend/src/app/vehicles/components/base-vehicles-table/base-vehicles-table.component.html

Closes #22 
Breaks apart and conditionally shows fields for route duration, route distance, and travel distance limits in the pre-solve Vehicle table.

Improve vehicle table

---

application/frontend/src/app/core/components/base-edit-vehicle-dialog/base-edit-vehicle-dialog.component.ts

Check for startTimeWindow before parsing startTime on vehicle edit dialog

---

application/frontend/src/app/core/reducers/request-settings.reducer.ts

Add optional chaining to constraint relaxations on update

---

application/frontend/src/app/core/effects/upload.effects.spec.ts
application/frontend/src/app/core/effects/upload.effects.ts

Add warning for user that injected routes are ignored when iterating on a solution.
Closes #44

Add warning message when injected routes are uploaded

---

application/frontend/src/app/core/containers/pre-solve-shipment-model-settings/pre-solve-shipment-model-settings.component.ts

Change save flow for shipment type requirements

---

application/frontend/src/app/core/containers/pre-solve-shipment-model-settings/pre-solve-shipment-model-settings.component.ts

Check for null selectedIndex before calculating precedence options

---

application/frontend/src/app/core/containers/map/map.component.ts

Addresses the following issues:
- Bounds incorrectly getting set when page is first loaded
- Add shipment and add vehicle buttons properly sync to page changes

Map bugfixes

---

application/frontend/src/app/shared/components/points-of-interest/points-of-interest.component.html
application/frontend/src/app/shared/components/points-of-interest/points-of-interest.component.scss
application/frontend/src/assets/images/dropoff.svg
application/frontend/src/assets/images/pickup.svg
application/frontend/src/styles/main.scss

Replaces a few outdated icons for pickups and deliveries with the new designs.

fix: Update old icons

---

application/frontend/src/app/shared/components/timezone-edit/timezone-edit.component.html
application/frontend/src/app/shared/components/timezone-edit/timezone-edit.component.scss
application/frontend/src/app/shared/components/timezone-edit/timezone-edit.component.ts

- Show offsets in GMT
- Sort list alphabetically
- Update styling to make entries more readable

feat: Make timezone selector more user friendly

---

application/frontend/src/app/core/components/base-vehicle-info-window/base-vehicle-info-window.component.html
application/frontend/src/app/core/components/base-vehicle-info-window/base-vehicle-info-window.component.ts
application/frontend/src/app/core/components/base-visit-request-info-window/base-visit-request-info-window.component.ts
application/frontend/src/app/core/models/route-metadata-filter.ts
application/frontend/src/app/core/selectors/routes-metadata.selectors.ts
application/frontend/src/app/routes-metadata/components/base-routes-metadata-table/base-routes-metadata-table.component.html
application/frontend/src/app/routes-metadata/models/route-metadata-column.model.ts
application/frontend/src/app/routes-metadata/models/route-metadata.model.ts
application/frontend/src/app/shared/components/table/table.component.scss
application/frontend/src/app/shared/pipes/format-hard-time-window.pipe.spec.ts
application/frontend/src/app/shared/pipes/format-seconds-date.pipe.ts
application/frontend/src/app/shared/pipes/format-timestamp.pipe.ts
application/frontend/src/app/shipments-metadata/components/base-shipments-metadata-table/base-shipments-metadata-table.component.html
application/frontend/src/app/util/time-translation.spec.ts
application/frontend/src/app/util/time-translation.ts
application/frontend/src/app/util/time-window.spec.ts
application/frontend/src/app/util/time-window.ts

- Show route distance in vehicle info window
- Show route distance in table view
- Show the total and max used vehicle capacity for each route in table view
- Rename "Traveled Time" to "Route Duration" to clarify what the metric is tracking
- Remove unimplemented columns that were still in the columns toggle list

feat: Improve metadata displays in post-solve views

---

application/frontend/src/app/core/components/base-main-nav/base-main-nav.component.spec.ts
application/frontend/src/app/core/components/dataset/dataset.component.spec.ts
application/frontend/src/app/core/components/map-add-buttons/map-add-buttons.component.spec.ts
application/frontend/src/app/core/components/precedence-rules-dialog/precedence-rules-dialog.component.spec.ts
application/frontend/src/app/core/components/shipment-type-incompatibility-dialog/shipment-type-incompatibility-dialog.component.spec.ts
application/frontend/src/app/core/components/shipment-type-requirement-dialog/shipment-type-requirement-dialog.component.spec.ts
application/frontend/src/app/core/components/top-bar/top-bar.component.spec.ts
application/frontend/src/app/core/containers/app/app.component.spec.ts
application/frontend/src/app/core/containers/csv-help-dialog/csv-help-dialog.component.spec.ts
application/frontend/src/app/core/containers/routes-chart-control-bar/routes-chart-control-bar.component.spec.ts
application/frontend/src/app/core/containers/scenario-solution-help-dialog/scenario-solution-help-dialog.component.spec.ts
application/frontend/src/app/core/containers/shipment-model-settings/shipment-model-settings.component.spec.ts
application/frontend/src/app/core/containers/travel-simulator/travel-simulator.component.spec.ts
application/frontend/src/app/core/containers/upload-dialog/upload-dialog.component.spec.ts
application/frontend/src/app/routes-chart/containers/routes-row/routes-row.component.spec.ts
application/frontend/src/app/scenario-planning/containers/scenario-planning/scenario-planning.component.spec.ts
application/frontend/src/app/shared/components/break-request-form/break-request-form.component.spec.ts
application/frontend/src/app/shared/components/undo-redo/undo-redo.component.spec.ts
application/frontend/src/app/shipments/containers/shipments/shipments.component.spec.ts
application/frontend/src/app/vehicles/components/base-vehicles-table/base-vehicles-table.component.ts
application/frontend/src/app/vehicles/containers/vehicles/vehicles.component.spec.ts

Resolves a number of warnings and errors in the application's unit tests.

fix: Fix warnings and errors from tests

---

application/frontend/src/app/core/containers/routes-chart-control-bar/routes-chart-control-bar.component.ts
application/frontend/src/app/core/containers/scenario-kpis/scenario-kpis.component.html
application/frontend/src/app/core/containers/scenario-kpis/scenario-kpis.component.spec.ts
application/frontend/src/app/core/containers/scenario-kpis/scenario-kpis.component.ts
application/frontend/src/app/core/models/scenario-kpis.ts
application/frontend/src/app/shared/components/load-demands-metrics/load-demands-metrics.component.html
application/frontend/src/app/shared/components/load-demands-metrics/load-demands-metrics.component.scss
application/frontend/src/app/shared/components/load-demands-metrics/load-demands-metrics.component.spec.ts
application/frontend/src/app/shared/components/load-demands-metrics/load-demands-metrics.component.ts
application/frontend/src/app/shared/shared.module.ts
application/frontend/src/styles/main.scss

Improves the styling of the metrics panels and adds vehicle capacity to the list of scenario metrics.

feat: Pre solve metrics panel updates

---

application/frontend/src/app/core/actions/routes-chart.actions.ts
application/frontend/src/app/core/reducers/routes-chart.reducer.ts
application/frontend/src/app/core/selectors/visit.selectors.ts
application/frontend/src/app/core/services/map.service.ts
application/frontend/src/app/routes-chart/components/base-routes-row/base-routes-row.component.html
application/frontend/src/app/routes-chart/components/base-routes-row/base-routes-row.component.ts
application/frontend/src/app/routes-chart/containers/routes-row/routes-row.component.html
application/frontend/src/app/routes-chart/containers/routes-row/routes-row.component.spec.ts
application/frontend/src/app/routes-chart/containers/routes-row/routes-row.component.ts
application/frontend/src/app/shared/components/points-of-interest/points-of-interest.component.ts
application/frontend/src/config.json

Upon clicking a stop, or group of stops, on the timeline view, zoom to the bounding box of those stops on the map and filter data to that route.

feat: Zoom to points of interest

---

application/frontend/src/app/core/containers/upload-dialog/upload-dialog.component.ts

Thank you for opening a Pull Request!
---
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #<issue_number_goes_here> 🦕

fix: Add default array for parsing waypoints

---

application/frontend/package-lock.json
application/frontend/package.json

Updates frontend protobufjs dependency

chore: update protobufjs

---

application/frontend/src/app/core/components/confirm-bulk-edit-dialog/confirm-bulk-edit-dialog.component.html
application/frontend/src/app/core/components/confirm-bulk-edit-dialog/confirm-bulk-edit-dialog.component.ts
application/frontend/src/app/core/containers/pre-solve-edit-shipment-dialog/pre-solve-edit-shipment-dialog.component.ts
application/frontend/src/app/core/containers/pre-solve-edit-vehicle-dialog/pre-solve-edit-vehicle-dialog.component.ts

fix: Confirm bulk edit for vehicles or shipments depending on trigger

---

application/frontend/src/app/core/components/base-visit-request-info-window/base-visit-request-info-window.component.html
application/frontend/src/app/core/components/base-visit-request-info-window/base-visit-request-info-window.component.ts
application/frontend/src/app/core/services/base-visit-request-layer.service.ts

Adds pre-solve visit request info windows to the map.

feat: click pre solve visits

---

application/frontend/src/app/core/services/csv.service.spec.ts
application/frontend/src/app/core/services/csv.service.ts
application/frontend/src/app/routes-chart/components/base-routes-row/base-routes-row.component.ts
application/frontend/src/app/routes-chart/containers/routes-row/routes-row.component.spec.ts
application/frontend/src/app/shared/components/load-demands-metrics/load-demands-metrics.component.spec.ts

Fixes vehicle imports to properly parse UnloadingPolicy values. Also cleans up a few testing issues.

fix: CSV unloading policy

---

application/frontend/src/app/core/services/csv.service.spec.ts
application/frontend/src/app/core/services/csv.service.ts

fix: check for geocode object before querying error

---

application/frontend/src/app/core/containers/vehicles-control-bar/vehicles-control-bar.component.html
application/frontend/src/app/core/containers/vehicles-control-bar/vehicles-control-bar.component.ts

fix: Support shipment model settings on vehicle tab

---

application/frontend/src/app/core/components/transition-attributes-dialog/transition-attributes-dialog.component.html
application/frontend/src/app/core/components/transition-attributes-dialog/transition-attributes-dialog.component.ts
application/frontend/src/app/util/validators.ts

feat: Add cost per kilometer below soft max to transition attributes

---

application/package-lock.json
application/package.json

Updates application level dependencies for setting up the local environment.

chore: upgrade lerna and dotenv

---

README.md
application/frontend/README.md
docs/architecture.md
docs/deployment.md
docs/project.md

docs: remove cfr references

---

training/module2-exercise1/solution/scenario.json
training/module2-exercise1/start/scenario.json
training/module2-exercise2/solution/scenario.json
training/module2-exercise2/start/scenario.json
training/module2-exercise3/solution/scenario.json
training/module2-exercise3/start/scenario.json
training/module3-exercise1/solution/scenario.json
training/module3-exercise1/start/scenario.json
training/module3-exercise2/solution/scenario.json
training/module3-exercise2/start/scenario.json
training/module3-exercise3/solution/scenario.json
training/module3-exercise3/start/scenario.json
training/module3-exercise4/solution/scenario.json
training/module3-exercise4/start/scenario.json
training/module3-exercise5/solution/scenario.json
training/module3-exercise5/start/scenario.json
training/module3-exercise6/solution/scenario.json
training/module3-exercise6/start/scenario.json

**Feature Request:** https://github.com/googlemaps/js-route-optimization-app/issues/246
This is sample training data that aligns with the *in-development* training courses for GMP RO. Currently 2 modules of the training have exercises that require the students to start from a example data set (provided here).
The fictitious company used in the training courses is called "Cymbol Logisitcs" and all shipments are made up for fake "Gizmos and Widgets". No real world data (other than lat/lngs) are used in this example data.

GMPRO Training Exercises files
