googlemaps/js-route-optimization-app

- README.md
- application/frontend/src/app/core/components/base-documentation-dialog/base-documentation-dialog.component.ts
- application/frontend/src/assets/docs/documentation.md
- docs/README.md
Add links to user guide markdown doc through the repo. Sets the `baseUrl` in the `marked`  options, to keep relative paths to image assets consistent.
Closes #4
> Add user guide

- application/frontend/src/app/shipments-metadata/components/base-shipments-metadata-table/base-shipments-metadata-table.component.html
On the shipment metadata view, visit request durations always display as "00:00" due to trying to cast the duration object to a number. This removes the casting so durations display correctly.
**Current**
**This PR**
> Fix visit request duration display on shipment metadata view

- application/frontend/src/app/core/selectors/timeline.selectors.ts
Closes #23
Timeline selector assumes there is always at least one driven travel step, which may not be the case, such as when a vehicle has no start or end location and only one stop to make. Checking for the existence of the last travel step before writing to it allows the timeline to properly support this situation.
> Check for lastTravelSegment before writing to it

- application/frontend/src/app/core/effects/dispatcher.effects.ts
Removes the condition that the user be in a pre-solve view to switch to the solution view automatically when a solution is loaded. New flow is that solution view will always become active when a solution loads.
Closes #27
> Always switch to solution view after solution is loaded

- application/frontend/src/app/core/services/pdf-download.service.ts
Closes #26 
Adds support to PDF exports for routes with no drive time and routes with no drive time and no visits. In the event of no driving and no visits, a map of the solution bounds is used.
> Handle routes with no drive time and/or no visits in PDF export

- application/frontend/src/app/core/services/pdf-download.service.ts
Addresses #36. Check for the existence of custom map options before trying to parse them into the syntax required for Static Maps API for use with PDF export. Result is a functional PDF export using the default Google Maps style.
> Check for custom map options during PDF generation

- application/frontend/src/app/core/containers/pre-solve-shipment-model-settings/pre-solve-shipment-model-settings.component.html
- application/frontend/src/app/core/containers/pre-solve-shipment-model-settings/pre-solve-shipment-model-settings.component.ts
Closes #42
Using virtual scroll containers in conjunction with mat-select is not currently supported by Angular Material. The result is that item selections outside of the rendered list will appear as empty since no valid selection has been made as far as the component is concerned.
To fix the display of precedence rules, this patch copies the current selection to the top of the virtual-scroll list so that it is always "in bounds" and will therefore be rendered.
> Copy selected precedence rule shipments to top of list

- application/frontend/src/app/core/containers/pre-solve-global-settings/pre-solve-global-settings.component.html
Partially address #44, with additional fix(es) to come.
Because uploaded injected solutions aren't fully supported in the app, it is possible for the app to check the toggle for using an injected solution while also having it locked from editing. This fix requires that a solution in the application exists before enabling or checking the injected solution toggle.
> Keep injected solution toggle disabled unless application solution exists

- application/frontend/src/app/core/components/base-edit-vehicle-dialog/base-edit-vehicle-dialog.component.ts
- application/frontend/src/app/core/containers/pre-solve-edit-vehicle-dialog/pre-solve-edit-vehicle-dialog.component.ts
Previous way of deleting BreakRules was to write an empty object to the store, but since upserts work as a partial update and not a complete overwrite, writing an empty object actually results in those fields not updating. Suggested alternative is to explicitly set those fields as `undefined`, as is done here.
Closes #57
> Overwrite empty BreakRules

- deployment/fleetrouting-app.tf
Increase Cloud Run memory to 512 MiB. 
Resolves #60
> Increase Cloud Run memory

- application/frontend/src/app/core/selectors/timeline.selectors.ts
> Exclude breaks from timeline that occur outside of the vehicle's day

- examples/two_step_routing/two_step_routing.py
- examples/two_step_routing/two_step_routing_test.py
1. Better handle allowedVehicleIndices in the two-step planner:
The original version used the intersection of allowed vehicle indices
for all shipments served from the parking location. When there are
significant variations in the allowed vehicles among the shipments, this
may lead to situations where the set of vehicles that can serve the
parking location is empty.
The modified version creates a new parking location visit for each group
of allowed vehicle indices used with the parking location. The new
version is equivalent to the original one when allowed vehicle indices
are not used, but it can create more shipments in the global model when
many different sets of allowed vehicles are used.
2. Fixed a couple of bugs discovered by more thorough testing:
- delivery time windows for …
> Add better support for allowedVehicleIndices and fix a few bugs in the two-step planner

- deployment/iap.tf
Add IAP service account resource, required to enable IAP for Cloud Run.
Reference: <https://cloud.google.com/iap/docs/enabling-cloud-run>
> Add IAP service account

- application/frontend/src/app/core/services/pdf-download.service.ts
- application/frontend/src/app/util/linear-referencing.ts
Closes #152 
This PR reduces the precision of marker lat/lngs and increases the level of simplification for route paths when generating maps for PDF export. These two changes reduce the length of the request parameters, allowing for previously failing PDF requests to now succeed.
As this is just a request length optimization, it is still possible that large requests will fail, and we may want to consider an alternative method for generating the PDF maps long term.
> perf: Optimize PDF map request parameters

- application/frontend/src/app/core/reducers/routes-chart.reducer.spec.ts
- application/frontend/src/app/core/reducers/routes-chart.reducer.ts
- application/frontend/src/app/core/selectors/post-solve-vehicle-layer.selectors.ts
- application/frontend/src/app/core/selectors/post-solve-visit-request-layer.selectors.ts
- application/frontend/src/app/core/selectors/route-layer.selectors.ts
- application/frontend/src/app/core/selectors/routes-chart.selectors.ts
- application/frontend/src/app/core/selectors/routes-metadata.selectors.ts
Updates the post-solve map to use the selections and filters of the current view (Timeline or Table) independent of one another.
> feat: Page dependent post-solve map selections

- docs/development.md
Updates `docs/development.md` to remove references to Cloud Fleet Routing and updates the roles and APIs that must be enabled to run the application.
Fixes #156
> docs: Update development docs

- application/frontend/src/app/core/containers/csv-upload-dialog/csv-upload-dialog.component.ts
- application/frontend/src/app/core/services/csv.service.spec.ts
- application/frontend/src/app/core/services/csv.service.ts
Properly parse travel modes from CSVs so that valid enum values are stored internally. As an additional safety check, adds additional user-facing validation when parsing vehicles.
Fixes #177
> fix: CSV upload parsing and validation

- application/frontend/src/app/core/actions/map.actions.ts
- application/frontend/src/app/core/components/map-add-buttons/map-add-buttons.component.scss
- application/frontend/src/app/core/containers/map/map.component.css
- application/frontend/src/app/core/containers/map/map.component.html
- application/frontend/src/app/core/containers/map/map.component.ts
- application/frontend/src/app/core/models/map.ts
- application/frontend/src/app/core/reducers/map.reducer.ts
- application/frontend/src/app/core/selectors/map.selectors.ts
- application/frontend/src/app/core/selectors/post-solve-vehicle-layer.selectors.ts
- application/frontend/src/app/core/selectors/pre-solve-vehicle-layer.selectors.ts
- application/frontend/src/app/core/selectors/route-layer.selectors.ts
Allows the user to toggle vehicle and shipment layers in the pre-solve view similar to the current implementation in the post-solve view.
> feat: Pre solve map layers controls

- application/frontend/angular.json
- application/frontend/src/app/core/components/precedence-rules-dialog/precedence-rules-dialog.component.spec.ts
- application/frontend/src/app/core/components/precedence-rules-dialog/precedence-rules-dialog.component.ts
- application/frontend/src/app/core/containers/pre-solve-edit-shipment-dialog/pre-solve-edit-shipment-dialog.component.ts
- application/frontend/src/app/core/effects/dispatcher-api.effects.ts
- application/frontend/src/app/core/effects/pre-solve-shipment.effects.ts
- application/frontend/src/app/core/selectors/capacity-quantity.selectors.ts
- application/frontend/src/app/core/selectors/denormalize.selectors.ts
- application/frontend/src/app/core/selectors/edit-visit.selectors.ts
- application/frontend/src/app/core/selectors/point-of-interest.selectors.ts
- application/frontend/src/app/core/selectors/pre-solve-shipment.selectors.ts
- application/frontend/src/app/core/selectors/routes-metadata.selectors.ts
- application/frontend/src/app/core/selectors/shipment.selectors.ts
- application/frontend/src/app/core/selectors/shipments-metadata.selectors.ts
- application/frontend/src/app/core/selectors/validation.selectors.ts
- application/frontend/src/app/core/selectors/visit-request.selectors.ts
Addresses some testing issues by abstracting entity selectors so they can be mocked. Also declares additional CommonJS dependencies to reduce warnings.
> chore: Test improvements

- application/frontend/src/app/core/containers/upload-dialog/upload-dialog.component.ts
Removes thrown errors from upload validation and instead returns an object, allowing zip to be properly crawled while maintaining vaildation results.
Also fixes a validation bug where previous zip errors would take precedence over more recent file upload errors.
Closes #237
> fix: zip validation order
